# Generated by Django 5.2 on 2025-04-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment'), ('SALES', 'Sales'), ('SPORTS', 'Sports'), ('EDUCATION', 'Education'), ('TECHNOLOGY', 'Technology'), ('HEALTH', 'Health'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
